name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every midnight
  workflow_dispatch: # Allows you to run it manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
